apiVersion: v1
kind: Namespace
metadata:
  name: legaltech
  labels:
    name: legaltech
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production